move files

diff --git a/.github/workflows/app.yml b/.github/workflows/app.yml
--- a/.github/workflows/app.yml
+++ b/.github/workflows/app.yml
@@ -40,10 +40,36 @@ jobs:
       - name: Log in to GitHub Container Registry
         run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u $GH_USERNAME --password-stdin
 
+      - name: Clear VM Directory
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ env.VM_HOST }}
+          username: justicea83
+          key: ${{ (env.CURRENT_ENV == 'dev' && secrets.VM_SSH_SECRET_DEV) || (env.CURRENT_ENV == 'prod' && secrets.VM_SSH_SECRET_PROD) }}
+          script: |
+            cd /home/justicea83
+            rm -rf docker-compose.ta.${{ env.CURRENT_ENV }}.yml
+
+      - name: Transfer docker-compose to VM
+        run: |
+          # Write the SSH private key to a temporary file
+          if [[ "${{ env.CURRENT_ENV }}" == "dev" ]]; then
+            echo "${{ secrets.VM_SSH_SECRET_DEV }}" > ssh_key
+          elif [[ "${{ env.CURRENT_ENV }}" == "prod" ]]; then
+            echo "${{ secrets.VM_SSH_SECRET_PROD }}" > ssh_key
+          fi
+
+          chmod 600 ssh_key
+
+          scp -o StrictHostKeyChecking=no -i ssh_key docker-compose.ta.${{ env.CURRENT_ENV }}.api.yml justicea83@${{ env.VM_HOST }}:/home/justicea83
+
+          # Clean up by removing the temporary SSH key file
+          rm -f ssh_key
+
       - name: Build and push images with Docker Compose
         run: |
-          docker compose -f docker-compose.prod.yml build
-          docker compose -f docker-compose.prod.yml push
+          docker compose -f docker-compose.ta.${{ env.CURRENT_ENV }}.yml build
+          docker compose -f docker-compose.ta.${{ env.CURRENT_ENV }}.yml push
 
       - name: Deploy to VM
         uses: appleboy/ssh-action@master
@@ -53,30 +79,8 @@ jobs:
           username: justicea83
           key: ${{ (env.CURRENT_ENV == 'dev' && secrets.VM_SSH_SECRET_DEV) || (env.CURRENT_ENV == 'prod' && secrets.VM_SSH_SECRET_PROD) }}
           script: |
-            if [ $(docker ps -a | grep taskflow-hr-app | wc -l) -gt 0 ]; then
-              docker stop taskflow-hr-app
-              docker rm taskflow-hr-app
-            fi
-            docker image prune -a -f
-            docker pull ghcr.io/justicea83/orangehrm:latest
-            docker run -d --name taskflow-hr-app --network taskflow_hr_shared --restart unless-stopped ghcr.io/justicea83/orangehrm:latest
-          
-
-      - name: Deploy taskflow-hr-app-nginx to VM
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ env.VM_HOST }}
-          command_timeout: 200m
-          username: justicea83
-          key: ${{ (env.CURRENT_ENV == 'dev' && secrets.VM_SSH_SECRET_DEV) || (env.CURRENT_ENV == 'prod' && secrets.VM_SSH_SECRET_PROD) }}
-          script: |
-            if [ $(docker ps -a | grep taskflow-hr-app-nginx | wc -l) -gt 0 ]; then
-              docker stop taskflow-hr-app-nginx
-              docker rm taskflow-hr-app-nginx
-            fi
-            docker image prune -a -f
-            docker pull ghcr.io/justicea83/orangehrm_nginx:latest
-            docker run -d -p 8000:80 --name taskflow-hr-app-nginx --network taskflow_hr_shared --restart unless-stopped ghcr.io/justicea83/orangehrm_nginx:latest
+            docker compose -f docker-compose.ta.${{ env.CURRENT_ENV }}.yml pull
+            docker compose -f docker-compose.ta.${{ env.CURRENT_ENV }}.yml up -d --build
 
       - name: Cleanup .env file
         run: rm -rf .env
